### ISSUE TITLE
npm run plugin.tscwatch - Does not apply changes in plugin to the demo

### ISSUE THREAD

**Issue by NathanWalker** [NativeScript/nativescript-plugin-seed#19] opened 2017-07-08 17:35 UTC
I would assume the way this is documented that running `npm run plugin.tscwatch` would apply any changes I make in the plugin files and update the running demo in the Simulator however with 2 terminal windows open, one with `npm run plugin.tscwatch` and the other running `npm run demo.ios`, when making changes to plugin files, the running demo does not respond or update.

**Comment by radeva** [comment] 2017-07-10 13:26
Could you confirm that you haven't deleted the node_modules in the demo before that? Cleaning node_modules in the demo will clear the link to the plugin so you need to run `npm run plugin.link` after that to recreate the link. This might be the reason for this issue.

**Comment by NathanWalker** [comment] 2017-07-11 19:18
@radeva `npm run plugin.link` does not work :(

When doing that, it includes the `node_modules` from the `src` folder itself and you get a wall of TypeScript errors:
```
"audio", "beacon", "cspreport", "download", "embed", "eventsource", "favicon", "fetch",
      ~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(5,5): error TS2300: Duplicate identifier '"audio"'.



5     "audio", "beacon", "cspreport", "download", "embed", "eventsource", "favicon", "fetch",
               ~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(5,14): error TS2300: Duplicate identifier '"beacon"'.



5     "audio", "beacon", "cspreport", "download", "embed", "eventsource", "favicon", "fetch",
                         ~~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(5,24): error TS2300: Duplicate identifier '"cspreport"'.


5     "audio", "beacon", "cspreport", "download", "embed", "eventsource", "favicon", "fetch",
                                      ~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(5,37): error TS2300: Duplicate identifier '"download"'.


5     "audio", "beacon", "cspreport", "download", "embed", "eventsource", "favicon", "fetch",
                                                  ~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(5,49): error TS2300: Duplicate identifier '"embed"'.



5     "audio", "beacon", "cspreport", "download", "embed", "eventsource", "favicon", "fetch",
                                                           ~~~~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(5,58): error TS2300: Duplicate identifier '"eventsource"'.


5     "audio", "beacon", "cspreport", "download", "embed", "eventsource", "favicon", "fetch",
                                                                          ~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(5,73): error TS2300: Duplicate identifier '"favicon"'.



5     "audio", "beacon", "cspreport", "download", "embed", "eventsource", "favicon", "fetch",
                                                                                     ~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(5,84): error TS2300: Duplicate identifier '"fetch"'.



6     "font", "form", "frame", "hyperlink", "iframe", "image", "imageset", "import",
      ~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(6,5): error TS2300: Duplicate identifier '"font"'.


6     "font", "form", "frame", "hyperlink", "iframe", "image", "imageset", "import",
              ~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(6,13): error TS2300: Duplicate identifier '"form"'.



6     "font", "form", "frame", "hyperlink", "iframe", "image", "imageset", "import",
                      ~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(6,21): error TS2300: Duplicate identifier '"frame"'.


6     "font", "form", "frame", "hyperlink", "iframe", "image", "imageset", "import",
                               ~~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(6,30): error TS2300: Duplicate identifier '"hyperlink"'.



6     "font", "form", "frame", "hyperlink", "iframe", "image", "imageset", "import",
                                            ~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(6,43): error TS2300: Duplicate identifier '"iframe"'.


6     "font", "form", "frame", "hyperlink", "iframe", "image", "imageset", "import",
                                                      ~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(6,53): error TS2300: Duplicate identifier '"image"'.



6     "font", "form", "frame", "hyperlink", "iframe", "image", "imageset", "import",
                                                               ~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(6,62): error TS2300: Duplicate identifier '"imageset"'.



6     "font", "form", "frame", "hyperlink", "iframe", "image", "imageset", "import",
                                                                           ~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(6,74): error TS2300: Duplicate identifier '"import"'.



7     "internal", "location", "manifest", "object", "ping", "plugin", "prefetch", "script",
      ~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(7,5): error TS2300: Duplicate identifier '"internal"'.



7     "internal", "location", "manifest", "object", "ping", "plugin", "prefetch", "script",
                  ~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(7,17): error TS2300: Duplicate identifier '"location"'.


7     "internal", "location", "manifest", "object", "ping", "plugin", "prefetch", "script",
                              ~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(7,29): error TS2300: Duplicate identifier '"manifest"'.


7     "internal", "location", "manifest", "object", "ping", "plugin", "prefetch", "script",
                                          ~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(7,41): error TS2300: Duplicate identifier '"object"'.


7     "internal", "location", "manifest", "object", "ping", "plugin", "prefetch", "script",
                                                    ~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(7,51): error TS2300: Duplicate identifier '"ping"'.


7     "internal", "location", "manifest", "object", "ping", "plugin", "prefetch", "script",
                                                            ~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(7,59): error TS2300: Duplicate identifier '"plugin"'.


7     "internal", "location", "manifest", "object", "ping", "plugin", "prefetch", "script",
                                                                      ~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(7,69): error TS2300: Duplicate identifier '"prefetch"'.



7     "internal", "location", "manifest", "object", "ping", "plugin", "prefetch", "script",
                                                                                  ~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(7,81): error TS2300: Duplicate identifier '"script"'.


8     "serviceworker", "sharedworker", "subresource", "style", "track", "video", "worker",
      ~~~~~~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(8,5): error TS2300: Duplicate identifier '"serviceworker"'.


8     "serviceworker", "sharedworker", "subresource", "style", "track", "video", "worker",
                       ~~~~~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(8,22): error TS2300: Duplicate identifier '"sharedworker"'.


8     "serviceworker", "sharedworker", "subresource", "style", "track", "video", "worker",
                                       ~~~~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(8,38): error TS2300: Duplicate identifier '"subresource"'.



8     "serviceworker", "sharedworker", "subresource", "style", "track", "video", "worker",
                                                      ~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(8,53): error TS2300: Duplicate identifier '"style"'.



8     "serviceworker", "sharedworker", "subresource", "style", "track", "video", "worker",
                                                               ~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(8,62): error TS2300: Duplicate identifier '"track"'.



8     "serviceworker", "sharedworker", "subresource", "style", "track", "video", "worker",
                                                                        ~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(8,71): error TS2300: Duplicate identifier '"video"'.



8     "serviceworker", "sharedworker", "subresource", "style", "track", "video", "worker",
                                                                                 ~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(8,80): error TS2300: Duplicate identifier '"worker"'.



9     "xmlhttprequest", "xslt"
      ~~~~~~~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(9,5): error TS2300: Duplicate identifier '"xmlhttprequest"'.


9     "xmlhttprequest", "xslt"
                        ~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(9,23): error TS2300: Duplicate identifier '"xslt"'.


17 declare type HeaderInit = Headers|Array<string>;
                ~~~~~~~~~~

node_modules/tns-core-modules/tns-core-modules.d.ts(17,14): error TS2300: Duplicate identifier 'HeaderInit'.
```
And many more.

**Comment by radeva** [comment] 2017-07-12 07:02
@NathanWalker Could you provide some more info like:
 - do you run the application for Android or iOS
 - what versions of the CLI and runtimes are you using

**Comment by radeva** [comment] 2017-07-25 07:05
Hi @NathanWalker ,

We applied some fixes that should prevent the problem to happen again. Could you confirm it's all ok now?

Best regards,
Vesi

**Comment by radeva** [comment] 2017-08-03 13:39
Hi @NathanWalker ,

Since we haven't received any reply, we assume the problem is now solved and will close the issue.
In case you experience any problems, feel free to contact us again.

Best regards,
Vesi

**Closed by radeva** 2017-08-03 13:39 UTC
Labels: planned
