### ISSUE TITLE
[Proposal] Remove publish folder/scripts

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/nativescript-plugin-seed#164] opened 2019-08-18 16:07 UTC
Looking at what the publish scripts are doing isn't it better to completely remove them and add appropriate scripts in the `package.json` file in the `src` folder. Then just execute `npm pack` or `npm publish` commands from inside the `src` folder. I think much more intuitive, not to mention that those `.sh` scripts cannot be execute under Windows 😉

**Comment by elena-p** [comment] 2019-09-26 13:20
Duplicate of https://github.com/NativeScript/nativescript-plugin-seed/issues/77

**Closed by elena-p** 2019-09-26 13:20 UTC
Labels: proposal
