### ISSUE TITLE
unable to run demo.android

### ISSUE THREAD

**Issue by tmandekic** [NativeScript/nativescript-plugin-seed#27] opened 2017-07-24 14:55 UTC
I'm trying to run a basic nativescript-plugin-seed on windows 10. Everything works up to the npm run demo.android. Whole process succeeds (builds, installs), but when it tries to run it on an emulator (android avd),  the output is error.  See attached. 
<img width="923" alt="nativescript plugin demo error" src="https://user-images.githubusercontent.com/1731753/28529357-531fa10c-705e-11e7-9513-d8cbefa1fa60.PNG">
Is there anything that I should be doing differently? I followed 4 basic steps outlined in your readme. I have not done anything else.

**Comment by radeva** [comment] 2017-07-25 10:25
Hi @tmandekic ,

A similar issue was reported several months ago in the core NativeScript repository. You can see the [detailed thread](https://github.com/NativeScript/NativeScript/issues/4240). 

What's the current version of NativeScript you're using? Could you try to update it using `npm install -g nativescript` or just follow our [upgrade instructions](https://docs.nativescript.org/releases/upgrade-instructions).

Best regards,
Veselina

**Comment by radeva** [comment] 2017-08-03 13:41
Hi @tmandekic,

Since we haven't received any reply, we assume the problem is now solved and will close the issue.
In case you experience any problems, feel free to contact us again.

Best regards,
Vesеlina

**Closed by radeva** 2017-08-03 13:41 UTC
Labels: planned, windows
